// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/loan_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/loan_usecase.go -destination=internal/mocks/mock_loan_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "bookhub/internal/domain/repository"
	usecase "bookhub/internal/usecase"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLoanUseCase is a mock of LoanUseCase interface.
type MockLoanUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLoanUseCaseMockRecorder
	isgomock struct{}
}

// MockLoanUseCaseMockRecorder is the mock recorder for MockLoanUseCase.
type MockLoanUseCaseMockRecorder struct {
	mock *MockLoanUseCase
}

// NewMockLoanUseCase creates a new mock instance.
func NewMockLoanUseCase(ctrl *gomock.Controller) *MockLoanUseCase {
	mock := &MockLoanUseCase{ctrl: ctrl}
	mock.recorder = &MockLoanUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanUseCase) EXPECT() *MockLoanUseCaseMockRecorder {
	return m.recorder
}

// BorrowBook mocks base method.
func (m *MockLoanUseCase) BorrowBook(ctx context.Context, input usecase.BorrowBookInput) (*repository.LoanWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BorrowBook", ctx, input)
	ret0, _ := ret[0].(*repository.LoanWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BorrowBook indicates an expected call of BorrowBook.
func (mr *MockLoanUseCaseMockRecorder) BorrowBook(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BorrowBook", reflect.TypeOf((*MockLoanUseCase)(nil).BorrowBook), ctx, input)
}

// GetByID mocks base method.
func (m *MockLoanUseCase) GetByID(ctx context.Context, id uuid.UUID) (*repository.LoanWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*repository.LoanWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLoanUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLoanUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockLoanUseCase) List(ctx context.Context, page, limit int, userID *uuid.UUID, status *string) ([]*repository.LoanWithDetails, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, limit, userID, status)
	ret0, _ := ret[0].([]*repository.LoanWithDetails)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockLoanUseCaseMockRecorder) List(ctx, page, limit, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLoanUseCase)(nil).List), ctx, page, limit, userID, status)
}

// ReturnBook mocks base method.
func (m *MockLoanUseCase) ReturnBook(ctx context.Context, loanID uuid.UUID) (*repository.LoanWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnBook", ctx, loanID)
	ret0, _ := ret[0].(*repository.LoanWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReturnBook indicates an expected call of ReturnBook.
func (mr *MockLoanUseCaseMockRecorder) ReturnBook(ctx, loanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnBook", reflect.TypeOf((*MockLoanUseCase)(nil).ReturnBook), ctx, loanID)
}
