// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAvailableBooks = `-- name: CountAvailableBooks :one
SELECT COUNT(*) FROM books WHERE available_copies > 0
`

func (q *Queries) CountAvailableBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableBooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBooks = `-- name: CountBooks :one
SELECT COUNT(*) FROM books
`

func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (id, title, author, isbn, published_year, total_copies, available_copies, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, author, isbn, published_year, total_copies, available_copies, created_at, updated_at
`

type CreateBookParams struct {
	ID              uuid.UUID     `json:"id"`
	Title           string        `json:"title"`
	Author          string        `json:"author"`
	Isbn            string        `json:"isbn"`
	PublishedYear   sql.NullInt32 `json:"published_year"`
	TotalCopies     int32         `json:"total_copies"`
	AvailableCopies int32         `json:"available_copies"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Isbn,
		arg.PublishedYear,
		arg.TotalCopies,
		arg.AvailableCopies,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Isbn,
		&i.PublishedYear,
		&i.TotalCopies,
		&i.AvailableCopies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, isbn, published_year, total_copies, available_copies, created_at, updated_at FROM books WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Isbn,
		&i.PublishedYear,
		&i.TotalCopies,
		&i.AvailableCopies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByISBN = `-- name: GetBookByISBN :one
SELECT id, title, author, isbn, published_year, total_copies, available_copies, created_at, updated_at FROM books WHERE isbn = $1
`

func (q *Queries) GetBookByISBN(ctx context.Context, isbn string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByISBN, isbn)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Isbn,
		&i.PublishedYear,
		&i.TotalCopies,
		&i.AvailableCopies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailableBooks = `-- name: ListAvailableBooks :many
SELECT id, title, author, isbn, published_year, total_copies, available_copies, created_at, updated_at FROM books
WHERE available_copies > 0
ORDER BY title ASC
LIMIT $1 OFFSET $2
`

type ListAvailableBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAvailableBooks(ctx context.Context, arg ListAvailableBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Isbn,
			&i.PublishedYear,
			&i.TotalCopies,
			&i.AvailableCopies,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, isbn, published_year, total_copies, available_copies, created_at, updated_at FROM books
ORDER BY title ASC
LIMIT $1 OFFSET $2
`

type ListBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Isbn,
			&i.PublishedYear,
			&i.TotalCopies,
			&i.AvailableCopies,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET title = $2, author = $3, isbn = $4, published_year = $5,
    total_copies = $6, available_copies = $7, updated_at = $8
WHERE id = $1
RETURNING id, title, author, isbn, published_year, total_copies, available_copies, created_at, updated_at
`

type UpdateBookParams struct {
	ID              uuid.UUID     `json:"id"`
	Title           string        `json:"title"`
	Author          string        `json:"author"`
	Isbn            string        `json:"isbn"`
	PublishedYear   sql.NullInt32 `json:"published_year"`
	TotalCopies     int32         `json:"total_copies"`
	AvailableCopies int32         `json:"available_copies"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Isbn,
		arg.PublishedYear,
		arg.TotalCopies,
		arg.AvailableCopies,
		arg.UpdatedAt,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Isbn,
		&i.PublishedYear,
		&i.TotalCopies,
		&i.AvailableCopies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
