// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAvailableBooks(ctx context.Context) (int64, error)
	CountBooks(ctx context.Context) (int64, error)
	CountLoans(ctx context.Context) (int64, error)
	CountLoansByStatus(ctx context.Context, status string) (int64, error)
	CountLoansByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountLoansByUserAndStatus(ctx context.Context, arg CountLoansByUserAndStatusParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBook(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActiveByUserAndBook(ctx context.Context, arg GetActiveByUserAndBookParams) (Loan, error)
	GetBookByID(ctx context.Context, id uuid.UUID) (Book, error)
	GetBookByISBN(ctx context.Context, isbn string) (Book, error)
	GetLoanByID(ctx context.Context, id uuid.UUID) (Loan, error)
	GetLoanByIDWithDetails(ctx context.Context, id uuid.UUID) (GetLoanByIDWithDetailsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAvailableBooks(ctx context.Context, arg ListAvailableBooksParams) ([]Book, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
	ListLoans(ctx context.Context, arg ListLoansParams) ([]Loan, error)
	ListLoansByStatus(ctx context.Context, arg ListLoansByStatusParams) ([]Loan, error)
	ListLoansByStatusWithDetails(ctx context.Context, arg ListLoansByStatusWithDetailsParams) ([]ListLoansByStatusWithDetailsRow, error)
	ListLoansByUser(ctx context.Context, arg ListLoansByUserParams) ([]Loan, error)
	ListLoansByUserAndStatus(ctx context.Context, arg ListLoansByUserAndStatusParams) ([]Loan, error)
	ListLoansByUserAndStatusWithDetails(ctx context.Context, arg ListLoansByUserAndStatusWithDetailsParams) ([]ListLoansByUserAndStatusWithDetailsRow, error)
	ListLoansByUserWithDetails(ctx context.Context, arg ListLoansByUserWithDetailsParams) ([]ListLoansByUserWithDetailsRow, error)
	ListLoansWithDetails(ctx context.Context, arg ListLoansWithDetailsParams) ([]ListLoansWithDetailsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
