version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/"
    schema: "../../../../migrations/"
    gen:
      go:
        package: "sqlc"
        out: "."
        sql_package: "database/sql"
        emit_json_tags: true
        emit_prepared_queries: false
        emit_interface: true
        emit_exact_table_names: false
        emit_empty_slices: true
